stats-extractor:
  sync-time: ${SYNC_TIME}
  queries:
    cashflow:
      start: ${CASHFLOW_START} # '2022-03-01T00:00:00.000'
      period: ${CASHFLOW_PERIOD} # 60d
    transfers:
      start: ${TRANSFERS_START}
      period: ${TRANSFERS_PERIOD}
    mau:
      start: ${MAU_START}
      period: ${MAU_PERIOD}
    dau:
      start: ${DAU_START}
      period: ${DAU_PERIOD}
    transactions:
      start: ${TRANSACTIONS_START}
      period: ${TRANSACTIONS_PERIOD}


spring:
  datasource:
    core:
      jdbc-url: ${CORE_DB_URL}
      username: ${CORE_DB_USER}
      password: ${CORE_DB_PASS}
      driverClassName: org.postgresql.Driver
      hikari:
        maximum-pool-size: ${CORE_POOL_SIZE}
    api:
      jdbc-url: ${API_DB_URL}
      username: ${API_DB_USER}
      password: ${API_DB_PASS}
      driverClassName: org.postgresql.Driver
      hikari:
        maximum-pool-size: ${API_POOL_SIZE}
